#!/bin/bash
# Note:
# To set the Resolution to 800x600 call 'tvservice -e "DMT 9"'
# To set the Resolution to 1280x1024 call 'tvservice -e "DMT 32"'
# Higher resolutions consume a lot of gpu memory.

RESOLUTION=high #low|medium|high
test "$1" ==  "" || RESOLUTION="$1"

PLAYER=both #both|left|right
test "$2" ==  "" || PLAYER="$2"

# Timeout for camera calibration
WAIT=5000

# --pongUseShader select one shader for the whole game
# --pongCycleShaders [Num] switch shader after N scoring points
# Definition of the shaders: apps/raspivid/shaders/gl_scenes/pong*.glsl
SHADEROPTIONS="--pongUseShader 0"

echo "Starting with resolution '${RESOLUTION}' and player '${PLAYER}'"
echo "Waiting $WAIT ms on camera initialisation"

if [ "$RESOLUTION" = "high" ] ; then
./pong --player ${PLAYER} --hflip -x /dev/null -t 0  --preview '0,0,1920,1080' --gl --glwin '0,0,1920,1080' --glscene pong -o /dev/null --waitAndFix ${WAIT} ${SHADEROPTIONS}
fi

if [ "$RESOLUTION" = "med" ] ; then
./pong --player ${PLAYER} --hflip -x /dev/null -t 0  --preview '0,0,1280x1024' --gl --glwin '0,0,1280x1024' --glscene pong -o /dev/null --waitAndFix ${WAIT} ${SHADEROPTIONS}
fi

if [ "$RESOLUTION" = "low" ] ; then
./pong --player ${PLAYER} --hflip -x /dev/null -t 0  --preview '0,0,800,600' --gl --glwin '0,0,800,600' --glscene pong -o /dev/null --waitAndFix ${WAIT} ${SHADEROPTIONS}
fi
