#!/bin/bash
# Note:
# To set the Resolution to 800x600 call 'tvservice -e "DMT 9"'
# To set the Resolution to 1280x1024 call 'tvservice -e "DMT 32"'
# Higher resolutions consume a lot of gpu memory.

RESOLUTION=high #low|med|high
test "$1" ==  "" || RESOLUTION="$1"

PLAYER=both #both|left|right
test "$2" ==  "" || PLAYER="$2"

# Timeout for camera calibration
WAIT=5000

# --pongUseShader select one shader for the whole game
# --pongCycleShaders [Num] switch shader after N scoring points
# Definition of the shaders: apps/raspivid/shaders/gl_scenes/pong*.glsl
SHADEROPTIONS="--pongUseShader 0"

ENV="LD_LIBRARY_PATH=./lib:\${LD_LIBRARY_PATH}"
MAINCMD="./bin/pong --player ${PLAYER} -x /dev/null -o /dev/null -t 0 --gl --glscene pong --waitAndFix ${WAIT} ${SHADEROPTIONS}"
EXTRA_ARGS="--vflip"
#EXTRA_ARGS="--hflip -rot 90"

echo "Starting with resolution '${RESOLUTION}' and player '${PLAYER}'"
echo "Waiting $WAIT ms on camera initialisation"

if [ "$RESOLUTION" = "high" ] ; then
eval "$ENV $MAINCMD $EXTRA_ARGS --preview '0,0,1920,1080' --glwin '0,0,1920,1080'"
fi

if [ "$RESOLUTION" = "med" ] ; then
eval "$ENV $MAINCMD $EXTRA_ARGS --preview '0,0,1280,1024' --glwin '0,0,1280,1024'"
fi

if [ "$RESOLUTION" = "low" ] ; then
eval "$ENV $MAINCMD $EXTRA_ARGS --preview '0,0,800,600' --glwin '0,0,800,600'"
fi
